import { q, one } from "../db.js";
import { localDate } from "../util/dates.js";
import { buildHealthState, type HealthState, type CoachingMode } from "./healthState.js";
import { recall, learnRoutines, learnFromOutcomes, type Memory } from "./brain.js";
import { dailyBalance } from "./budget.js";
import { activityFor } from "./activity.js";
import * as safety from "./safety.js";
import { topSleepInsight } from "./sleep.js";

/**
 * The coach orchestrator.
 *
 * Deliberately *not* "ask the model what the user should do today". Candidate
 * actions are generated by deterministic rules over real data, then filtered,
 * ranked and capped. The model's job is to phrase the winners, not to decide
 * them.
 *
 * Three reasons for that split:
 *   - a rule cannot invent a number, and every action here cites real data;
 *   - ranking is auditable, so "why did it say that" has an answer;
 *   - it costs nothing to generate candidates, so the expensive call only ever
 *     phrases 1–3 things rather than reasoning over the whole day.
 */

export type Domain =
  | "nutrition" | "fitness" | "sleep" | "recovery"
  | "hydration" | "activity" | "habit";

export type CandidateAction = {
  domain: Domain;
  action: string;
  /** Why this, now. An action without a reason is a random suggestion. */
  reason: string;
  /** 0-100. Impact × confidence × how likely this person is to act. */
  score: number;
  confidence: number;
  /** Which findings produced it, kept for later analysis. */
  triggeredBy: string[];
};

/** Cap. More than three priorities is a list, not a priority. */
const MAX_ACTIONS = 3;
/** Below this an action is not worth a person's attention. */
const SCORE_FLOOR = 25;

type Signals = {
  state: HealthState;
  memories: Memory[];
  remainingKcal: number | null;
  remainingProtein: number | null;
  targetProtein: number | null;
  consumedKcal: number;
  mealsLogged: number;
  waterMl: number;
  waterTargetMl: number | null;
  steps: number;
  workoutsThisWeek: number;
  trainingDays: number;
  lastWorkoutDaysAgo: number | null;
  /** The single sleep finding worth acting on, if there is one. */
  sleepInsight: Awaited<ReturnType<typeof topSleepInsight>>;
  /** Local hour, so a routine deviation can be judged against the clock. */
  hourOfDay: number | null;
  isWeekend: boolean;
  /** 22:00–04:59. Past the point where training or a big meal helps. */
  isLateNight: boolean;
};

async function gatherSignals(userId: string, tz: string): Promise<Signals> {
  const today = localDate(tz);

  const [state, memories, targets, consumed, water, activity, workouts, fitness,
         sleepInsight] = await Promise.all([
      buildHealthState(userId, today),
      recall(userId, { limit: 12 }),
      one<any>(`SELECT calories, protein_g, water_ml FROM nutrition_targets WHERE user_id = $1`,
               [userId]),
      one<any>(
        `SELECT ROUND(SUM(i.grams * i.kcal_100g / 100))::int    AS calories,
                ROUND(SUM(i.grams * i.protein_100g / 100))::int AS protein_g,
                COUNT(DISTINCT m.id)::int                        AS meals
           FROM meals m JOIN meal_items i ON i.meal_id = m.id
          WHERE m.user_id = $1 AND m.logged_on = $2`, [userId, today]),
      one<any>(`SELECT COALESCE(SUM(ml),0)::int AS ml FROM water_logs
                 WHERE user_id = $1 AND logged_on = $2`, [userId, today]),
      activityFor(userId, tz, today),
      one<any>(
        `SELECT COUNT(*)::int AS this_week,
                MIN(CURRENT_DATE - performed_on)::int AS days_since
           FROM workouts
          WHERE user_id = $1 AND performed_on > CURRENT_DATE - 7`, [userId]),
      one<any>(`SELECT training_days FROM fitness_profile WHERE user_id = $1`, [userId]),
      topSleepInsight(userId, tz),
    ]) as any;

  const balance = dailyBalance(targets, consumed, activity);

  const localHour = Number(
    new Intl.DateTimeFormat("en-GB", { timeZone: tz, hour: "2-digit", hour12: false })
      .format(new Date()));
  const weekday = new Date(`${today}T12:00:00Z`).getUTCDay();

  return {
    state,
    memories,
    hourOfDay: Number.isFinite(localHour) ? localHour : null,
    isWeekend: weekday === 0 || weekday === 6,
    isLateNight: localHour >= 22 || localHour < 5,
    remainingKcal: targets ? balance.remaining.calories : null,
    remainingProtein: targets ? balance.remaining.protein_g : null,
    targetProtein: targets?.protein_g ?? null,
    consumedKcal: consumed?.calories ?? 0,
    mealsLogged: consumed?.meals ?? 0,
    waterMl: water?.ml ?? 0,
    waterTargetMl: targets?.water_ml ?? null,
    steps: activity.steps,
    workoutsThisWeek: workouts?.this_week ?? 0,
    trainingDays: fitness?.training_days ?? 3,
    lastWorkoutDaysAgo: workouts?.days_since ?? null,
    sleepInsight,
  };
}

/**
 * Modifier from procedural memory.
 *
 * If someone has ignored six nutrition suggestions, a seventh is worth less
 * than something they actually act on. This is the whole point of tracking
 * outcomes — the coach should get better at knowing which levers work for
 * *this* person.
 */
function adherenceModifier(memories: Memory[], domain: Domain): number {
  const positive = memories.find(
    (m) => m.layer === "procedural" && m.content.includes(`on ${domain} suggestions`)
        && !m.content.includes("rarely"));
  const negative = memories.find(
    (m) => m.layer === "procedural" && m.content.includes(`rarely acts on ${domain}`));
  const effective = memories.find(
    (m) => m.layer === "procedural" && m.content.startsWith(`${domain} changes measurably help`));

  let modifier = 1;
  if (positive) modifier += 0.15;
  if (effective) modifier += 0.3;
  if (negative) modifier -= 0.4;
  return Math.max(0.3, modifier);
}

/**
 * Candidate generation.
 *
 * Every rule states a real number from the signals. None invents a target, and
 * none fires without the data it needs — a missing metric produces no action
 * rather than an action based on an assumed zero.
 */
function generateCandidates(s: Signals): CandidateAction[] {
  const out: CandidateAction[] = [];
  const mode = s.state.mode;

  const add = (c: Omit<CandidateAction, "score"> & { impact: number }) => {
    const modifier = adherenceModifier(s.memories, c.domain);
    out.push({
      domain: c.domain,
      action: c.action,
      reason: c.reason,
      confidence: c.confidence,
      triggeredBy: c.triggeredBy,
      score: Math.round(c.impact * c.confidence * modifier),
    });
  };

  // ── nutrition ───────────────────────────────────────────────────────────
  if (s.mealsLogged === 0) {
    add({
      domain: "habit", impact: 70, confidence: 1,
      action: "Log your first meal of the day",
      reason: "Nothing logged yet, and the rest of today's guidance depends on it.",
      triggeredBy: ["no_meals_logged"],
    });
  }

  if (s.remainingProtein != null && s.targetProtein != null && s.mealsLogged > 0) {
    const shortfall = s.remainingProtein;
    const proportion = shortfall / s.targetProtein;

    // Only worth raising once the day is far enough along to be a real gap.
    if (proportion > 0.5 && s.mealsLogged >= 2) {
      add({
        domain: "nutrition", impact: 80, confidence: 0.9,
        action: `Make your next meal protein-led — about ${Math.round(shortfall)}g to go`,
        reason: `You're ${Math.round(shortfall)}g short of your ${s.targetProtein}g protein target with most of the day gone.`,
        triggeredBy: ["protein_shortfall"],
      });
    }
  }

  // Over budget is stated without moralising — one day is not a failure.
  if (s.remainingKcal != null && s.remainingKcal < -200) {
    add({
      domain: "nutrition", impact: 45, confidence: 0.85,
      action: "Keep the rest of today light and pick it up tomorrow",
      reason: `You're about ${Math.abs(s.remainingKcal)} over today. One day doesn't undo a week.`,
      triggeredBy: ["over_budget"],
    });
  }

  // ── sleep ───────────────────────────────────────────────────────────────
  // From the sleep engine, which reasons about timing and regularity rather
  // than duration alone — and never about stages.
  if (s.sleepInsight?.action) {
    add({
      domain: "sleep",
      impact: s.sleepInsight.weight,
      confidence: s.sleepInsight.confidence === "high" ? 0.9
                : s.sleepInsight.confidence === "medium" ? 0.7 : 0.5,
      action: s.sleepInsight.action,
      reason: s.sleepInsight.finding,
      triggeredBy: ["sleep", s.sleepInsight.kind],
    });
  }

  if (s.state.sleep.confidence !== "none"
      && s.state.sleep.deviationPct != null
      && s.state.sleep.deviationPct <= -20) {
    add({
      domain: "sleep", impact: 75, confidence: 0.85,
      action: "Get to bed early tonight",
      reason: `Last night was ${Math.abs(s.state.sleep.deviationPct)}% below your usual, and that's what's driving today's lighter plan.`,
      triggeredBy: ["short_sleep"],
    });
  }

  // ── training and recovery ───────────────────────────────────────────────
  if (mode === "recovery") {
    add({
      domain: "recovery", impact: 90, confidence: 0.85,
      action: "Take today easy — a walk or some mobility rather than a session",
      reason: s.state.modeRationale.length
        ? `Your ${s.state.modeRationale[0]}, so recovery will do more than training today.`
        : "Your recent load and recovery signals suggest an easier day.",
      triggeredBy: ["recovery_mode", ...s.state.modeRationale],
    });
  } else if (s.workoutsThisWeek < s.trainingDays
             && (s.lastWorkoutDaysAgo == null || s.lastWorkoutDaysAgo >= 2)
             // Not at midnight. Suggesting a session someone cannot sensibly
             // do tonight is noise, and it makes the coach look like it isn't
             // paying attention.
             && !s.isLateNight) {
    add({
      domain: "fitness", impact: mode === "growth" ? 80 : 65,
      confidence: 0.8,
      action: "Get a session in today",
      reason: s.lastWorkoutDaysAgo == null
        ? `You're aiming for ${s.trainingDays} days a week and haven't trained yet this week.`
        : `${s.workoutsThisWeek} of ${s.trainingDays} sessions done, and it's been ${s.lastWorkoutDaysAgo} days.`,
      triggeredBy: ["training_gap"],
    });
  }

  // ── activity ────────────────────────────────────────────────────────────
  const steps = s.state.steps;
  if (steps.confidence !== "none" && steps.baseline != null && s.steps > 0) {
    if (s.steps < steps.baseline * 0.5 && !s.isLateNight) {
      add({
        domain: "activity", impact: 55, confidence: 0.75,
        action: "Add a short walk this evening",
        reason: `You're at ${s.steps.toLocaleString()} steps against a usual ${Math.round(steps.baseline).toLocaleString()}.`,
        triggeredBy: ["low_activity"],
      });
    }
  }

  // ── memory-driven ───────────────────────────────────────────────────────
  // The point of the brain. These rules cannot fire for a new user, which is
  // exactly what should make week 8 feel different from week 1.

  // A known routine that has not happened yet today.
  const mealRoutine = s.memories.find(
    (m) => m.layer === "routine" && /eats (breakfast|lunch|dinner) around/.test(m.content));

  if (mealRoutine && s.mealsLogged === 0 && s.hourOfDay != null) {
    const hourMatch = mealRoutine.content.match(/around (\d+)(am|pm)/);
    if (hourMatch) {
      const hour = Number(hourMatch[1]) + (hourMatch[2] === "pm" && hourMatch[1] !== "12" ? 12 : 0);
      // Only once the usual time has clearly passed.
      if (s.hourOfDay >= hour + 2) {
        add({
          domain: "habit", impact: 60, confidence: mealRoutine.confidence,
          action: "Log what you've eaten so far",
          reason: `You ${mealRoutine.content} and there's nothing down yet today.`,
          triggeredBy: ["routine_deviation", mealRoutine.content],
        });
      }
    }
  }

  // Weekend drop-off, on a weekend.
  const weekendGap = s.memories.find((m) => m.subject === "weekend_logging");
  if (weekendGap && s.isWeekend) {
    add({
      domain: "habit", impact: 55, confidence: weekendGap.confidence,
      action: "Keep logging through the weekend",
      reason: "Weekends are where your tracking usually slips — a couple of quick photos is enough.",
      triggeredBy: ["weekend_pattern"],
    });
  }

  // A lever that has demonstrably worked for this person before.
  const provenLever = s.memories.find(
    (m) => m.layer === "procedural" && /changes measurably help/.test(m.content));
  if (provenLever) {
    const domain = provenLever.content.split(" ")[0] as Domain;
    const already = out.some((c) => c.domain === domain);
    if (!already && ["sleep", "activity", "recovery", "nutrition"].includes(domain)) {
      add({
        domain, impact: 65, confidence: provenLever.confidence,
        action: domain === "sleep" ? "Protect your wind-down tonight"
              : domain === "activity" ? "Get a walk in"
              : domain === "recovery" ? "Keep today easy"
              : "Keep protein up at your next meal",
        reason: `${domain[0]!.toUpperCase()}${domain.slice(1)} changes have moved the needle for you before.`,
        triggeredBy: ["proven_lever", provenLever.content],
      });
    }
  }

  // ── hydration ───────────────────────────────────────────────────────────
  if (s.waterTargetMl && s.waterMl < s.waterTargetMl * 0.4
      && s.mealsLogged >= 2 && !s.isLateNight) {
    add({
      domain: "hydration", impact: 35, confidence: 0.7,
      action: "Have a glass of water",
      reason: `${(s.waterMl / 1000).toFixed(1)}L logged against a ${(s.waterTargetMl / 1000).toFixed(1)}L target.`,
      triggeredBy: ["low_hydration"],
    });
  }

  // Late at night the only genuinely useful thing is going to bed. Everything
  // above is about today, which is effectively over.
  if (s.isLateNight) {
    add({
      domain: "sleep", impact: 95, confidence: 0.9,
      action: "Wrap up and get to bed",
      reason: s.state.sleepRegularity.regularityScore != null
              && s.state.sleepRegularity.regularityScore < 60
        ? "Your bedtime moves around a lot, and that's the thing most worth steadying."
        : "It's late — today's already done, and sleep is what tomorrow runs on.",
      triggeredBy: ["late_night"],
    });
  }

  return out;
}

/**
 * Ranks and caps.
 *
 * One action per domain: three nutrition tips read as nagging, whereas one
 * each from nutrition, training and sleep reads as a plan.
 */
export function rank(candidates: CandidateAction[], mode: CoachingMode): CandidateAction[] {
  const byDomain = new Map<Domain, CandidateAction>();

  for (const c of candidates.sort((a, b) => b.score - a.score)) {
    if (!byDomain.has(c.domain)) byDomain.set(c.domain, c);
  }

  const ranked = [...byDomain.values()]
    .filter((c) => c.score >= SCORE_FLOOR)
    .sort((a, b) => b.score - a.score);

  // In recovery mode, ask for less. Piling on when someone is under-slept is
  // how a coach loses trust.
  const cap = mode === "recovery" ? 2 : MAX_ACTIONS;
  return ranked.slice(0, cap);
}

export type DailyBriefing = {
  date: string;
  mode: CoachingMode;
  /** Present tense, plain language, no score. */
  headline: string;
  actions: Array<CandidateAction & { id: string }>;
  /** Metrics with no data, so the UI can prompt rather than show zeros. */
  missing: string[];
  generated: boolean;
};

function headlineFor(mode: CoachingMode, s: Signals): string {
  const name = "";
  switch (mode) {
    case "recovery":
      return `Lighter day${name}. Your body's asking for a bit of slack, so today's plan is smaller on purpose.`;
    case "growth":
      return `Good day to push${name}. Sleep and recovery are where they should be.`;
    default:
      return s.mealsLogged === 0
        ? `Fresh start${name}. Log something and I'll tune the rest of the day around it.`
        : `Steady day${name}. Here's what matters most.`;
  }
}

/**
 * Builds today's briefing and persists the actions as recommendations, so the
 * loop can later ask whether they were followed and whether they helped.
 *
 * Idempotent per day: calling twice returns the same actions rather than
 * generating a second set.
 */
export async function dailyBriefing(
  userId: string,
  tz: string,
  opts: { regenerate?: boolean } = {}
): Promise<DailyBriefing> {
  const today = localDate(tz);

  const existing = await q<any>(
    `SELECT id, domain, action, reason, confidence, triggered_by, status
       FROM recommendations
      WHERE user_id = $1 AND offered_on = $2
      ORDER BY created_at`,
    [userId, today]
  );

  const signals = await gatherSignals(userId, tz);

  if (existing.length > 0 && !opts.regenerate) {
    return {
      date: today,
      mode: signals.state.mode,
      headline: headlineFor(signals.state.mode, signals),
      actions: existing.map((r: any) => ({
        id: r.id,
        domain: r.domain,
        action: r.action,
        reason: r.reason,
        confidence: Number(r.confidence),
        triggeredBy: r.triggered_by ?? [],
        score: 0,
      })),
      missing: signals.state.missing,
      generated: false,
    };
  }

  const candidates = generateCandidates(signals);
  // One thing at midnight. A list of priorities for a day that is over reads
  // as an app that has not noticed the time.
  const chosen = signals.isLateNight
    ? rank(candidates, signals.state.mode).slice(0, 1)
    : rank(candidates, signals.state.mode);

  // Persist so the outcome can be measured later. A recommendation nobody
  // recorded is a recommendation nobody can learn from.
  const stored: Array<CandidateAction & { id: string }> = [];
  for (const c of chosen) {
    const row = await one<{ id: string }>(
      `INSERT INTO recommendations
         (user_id, domain, action, reason, confidence, triggered_by, offered_on)
       VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id`,
      [userId, c.domain, c.action, c.reason, c.confidence,
       JSON.stringify(c.triggeredBy), today]
    );
    stored.push({ ...c, id: row!.id });
  }

  return {
    date: today,
    mode: signals.state.mode,
    headline: headlineFor(signals.state.mode, signals),
    actions: stored,
    missing: signals.state.missing,
    generated: true,
  };
}

/**
 * Measures whether yesterday's advice moved anything.
 *
 * Only claims a direction where a metric can actually be compared; everything
 * else stays "unknown" rather than being guessed. Overstating this would
 * poison the procedural memory it feeds.
 */
export async function measureOutcomes(userId: string, tz: string): Promise<number> {
  const today = localDate(tz);

  const pending = await q<any>(
    `SELECT r.id, r.domain, r.offered_on, r.status
       FROM recommendations r
       LEFT JOIN recommendation_outcomes o ON o.recommendation_id = r.id
      WHERE r.user_id = $1
        AND r.offered_on BETWEEN $2::date - 7 AND $2::date - 1
        AND o.id IS NULL`,
    [userId, today]
  );

  /** Which metric a domain is expected to move. */
  const METRIC: Partial<Record<Domain, string>> = {
    sleep: "sleep_minutes",
    activity: "steps",
    recovery: "hrv",
  };

  let measured = 0;

  for (const rec of pending) {
    const metric = METRIC[rec.domain as Domain];

    if (!metric) {
      // No measurable proxy — record that honestly rather than inventing one.
      await q(
        `INSERT INTO recommendation_outcomes (recommendation_id, user_id, direction)
         VALUES ($1,$2,'unknown')`, [rec.id, userId]);
      measured++;
      continue;
    }

    const window = await one<{ before: string | null; after: string | null }>(
      `SELECT
         AVG(value) FILTER (WHERE observed_on <  $3::date) AS before,
         AVG(value) FILTER (WHERE observed_on >= $3::date) AS after
       FROM health_observations
      WHERE user_id = $1 AND metric = $2
        AND observed_on BETWEEN $3::date - 7 AND $3::date + 3`,
      [userId, metric, rec.offered_on]
    );

    const before = window?.before == null ? null : Number(window.before);
    const after = window?.after == null ? null : Number(window.after);

    let direction = "unknown";
    if (before != null && after != null && before !== 0) {
      const change = ((after - before) / before) * 100;
      // 5% is the threshold below which this is noise.
      if (Math.abs(change) < 5) direction = "unchanged";
      else if (metric === "resting_hr") direction = change < 0 ? "improved" : "worse";
      else direction = change > 0 ? "improved" : "worse";
    }

    await q(
      `INSERT INTO recommendation_outcomes
         (recommendation_id, user_id, metric, before_value, after_value, direction)
       VALUES ($1,$2,$3,$4,$5,$6)`,
      [rec.id, userId, metric, before, after, direction]);
    measured++;
  }

  // Expire anything never responded to, so completion rates stay honest.
  await q(
    `UPDATE recommendations SET status = 'expired'
      WHERE user_id = $1 AND status = 'pending' AND offered_on < $2::date - 2`,
    [userId, today]);

  return measured;
}

/**
 * The nightly cycle: measure what happened, then learn from it.
 *
 * Runs lazily on request rather than on a timer — a single-replica deployment
 * does not need a scheduler, and lazy execution means a dormant account costs
 * nothing.
 */
export async function runLearningCycle(userId: string, tz: string) {
  const measured = await measureOutcomes(userId, tz);
  const [routines, outcomes] = await Promise.all([
    learnRoutines(userId),
    learnFromOutcomes(userId),
  ]);

  return {
    outcomesMeasured: measured,
    memoriesAdded: [...routines, ...outcomes].filter((r) => r.action === "ADD").length,
    memoriesUpdated: [...routines, ...outcomes].filter((r) => r.action === "UPDATE").length,
    memoriesReinforced: [...routines, ...outcomes].filter((r) => r.action === "REINFORCE").length,
  };
}
