import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { q, one } from "../db.js";
import { requireAuth } from "../middleware/auth.js";
import { localDate } from "../util/dates.js";
import { buildHealthState, metricState } from "../services/healthState.js";
import {
  allMemories, editMemory, forgetMemory, learnRoutines, learnFromOutcomes, recall,
} from "../services/brain.js";
import { dailyBriefing, runLearningCycle } from "../services/orchestrator.js";
import { planNotifications, recordEngagement } from "../services/notifications.js";
import { sleepSummary, clockLabel } from "../services/sleep.js";
import {
  onboardingPlan, saveScreen, skipScreen, finishOnboarding,
} from "../services/onboarding.js";
import { coachWelcome, recordWelcomeReply } from "../services/coachWelcome.js";

/**
 * Personal Health Brain endpoints.
 *
 * Split out of premium.ts deliberately — that file had grown to 30 endpoints
 * across 11 domains, which makes every change riskier than it needs to be.
 */
export default async function routes(app: FastifyInstance) {

  // ── normalized observations ───────────────────────────────────────────────
  /**
   * Ingest point for anything measured. One row per metric per day.
   *
   * Separate from /health/daily because that endpoint is a HealthKit rollup
   * with fixed columns; this accepts any metric, from any source, with a
   * confidence — which is what the state engine needs.
   */
  app.post("/observations", { preHandler: requireAuth }, async (req) => {
    const body = z.object({
      observations: z.array(z.object({
        metric: z.string().max(40),
        value: z.number(),
        observed_on: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
        source: z.enum(["healthkit", "manual", "derived", "photo"]).default("healthkit"),
        confidence: z.number().min(0).max(1).default(1),
      })).min(1).max(200),
    }).parse(req.body);

    const today = localDate(req.tz);
    let stored = 0;

    for (const o of body.observations) {
      await q(
        `INSERT INTO health_observations
           (user_id, observed_on, metric, value, source, confidence)
         VALUES ($1,$2,$3,$4,$5,$6)
         ON CONFLICT (user_id, observed_on, metric, source)
         DO UPDATE SET value = EXCLUDED.value,
                       confidence = EXCLUDED.confidence,
                       recorded_at = now()`,
        [req.userId, o.observed_on ?? today, o.metric, o.value, o.source, o.confidence]
      );
      stored++;
    }

    return { stored };
  });

  /** Health state: trends, baselines and confidence rather than raw numbers. */
  app.get("/health/state", { preHandler: requireAuth }, async (req) =>
    buildHealthState(req.userId, localDate(req.tz)));

  app.get("/health/metric/:metric", { preHandler: requireAuth }, async (req) => {
    const { metric } = z.object({ metric: z.string().max(40) }).parse(req.params);
    return metricState(req.userId, metric, localDate(req.tz));
  });

  // ── the daily briefing ────────────────────────────────────────────────────
  /**
   * Today's 1–3 priorities, with a reason for each.
   *
   * Actions are generated by rules over real data, not by asking a model what
   * the user should do — so every one cites a number, and none can be
   * invented. Idempotent per day.
   */
  app.get("/coach/briefing", { preHandler: requireAuth }, async (req) => {
    const { regenerate } = z.object({
      regenerate: z.coerce.boolean().default(false),
    }).parse(req.query);

    return dailyBriefing(req.userId, req.tz, { regenerate });
  });

  /**
   * Measures what last week's advice did, then learns from it.
   *
   * Lazy rather than scheduled: a single-replica deployment needs no worker,
   * and a dormant account costs nothing. The client calls this once a day.
   */
  app.post("/coach/learn-cycle", { preHandler: requireAuth }, async (req) =>
    runLearningCycle(req.userId, req.tz));

  // ── onboarding ────────────────────────────────────────────────────────────
  /**
   * The screens this user should see.
   *
   * Adaptive: anything already known is dropped, and a screen whose fields are
   * all known disappears entirely. Someone who has connected Health and filled
   * a profile may see three screens rather than eight.
   */
  app.get("/onboarding/plan", { preHandler: requireAuth }, async (req) => {
    const { answers } = z.object({
      answers: z.string().optional(),
    }).parse(req.query);

    const parsed = answers ? JSON.parse(answers) : {};
    return onboardingPlan(req.userId, parsed);
  });

  app.post("/onboarding/screen", { preHandler: requireAuth }, async (req) => {
    const { screen, answers, skipped } = z.object({
      screen: z.string().max(40),
      answers: z.record(z.any()).default({}),
      skipped: z.boolean().default(false),
    }).parse(req.body);

    if (skipped) await skipScreen(req.userId, screen);
    else await saveScreen(req.userId, screen, answers);

    // Recomputed rather than assumed: an answer can remove a later screen.
    return onboardingPlan(req.userId, answers);
  });

  app.post("/onboarding/finish", { preHandler: requireAuth }, async (req) => {
    await finishOnboarding(req.userId);
    return { completed: true };
  });

  /** The health profile, for the "what SnapCal knows" screen and for editing. */
  app.get("/health/profile", { preHandler: requireAuth }, async (req) => {
    const [schedule, conditions, allergies, meds, mind, profile] = await Promise.all([
      one(`SELECT * FROM daily_schedule WHERE user_id = $1`, [req.userId]),
      q(`SELECT id, condition, restriction FROM health_conditions WHERE user_id = $1`, [req.userId]),
      q(`SELECT id, allergen, kind, severity FROM user_allergies WHERE user_id = $1`, [req.userId]),
      q(`SELECT id, name, dose, frequency, times, purpose, kind, reminders
           FROM medications WHERE user_id = $1 AND active ORDER BY kind, name`, [req.userId]),
      one(`SELECT * FROM mind_profile WHERE user_id = $1`, [req.userId]),
      one(`SELECT primary_goal, secondary_goals, success_looks_like, work_type
             FROM profiles WHERE user_id = $1`, [req.userId]),
    ]);

    return { schedule, conditions, allergies, medications: meds, mind, goals: profile };
  });

  /** Anything here must be removable — it is the most sensitive data we hold. */
  app.delete("/health/conditions/:id", { preHandler: requireAuth }, async (req, reply) => {
    const { id } = z.object({ id: z.coerce.number() }).parse(req.params);
    const gone = await one(
      `DELETE FROM health_conditions WHERE id = $2 AND user_id = $1 RETURNING id`,
      [req.userId, id]);
    return gone ? { deleted: true } : reply.code(404).send({ error: "not_found" });
  });

  app.delete("/medications/:id", { preHandler: requireAuth }, async (req, reply) => {
    const { id } = z.object({ id: z.string().uuid() }).parse(req.params);
    const gone = await one(
      `DELETE FROM medications WHERE id = $2 AND user_id = $1 RETURNING id`,
      [req.userId, id]);
    return gone ? { deleted: true } : reply.code(404).send({ error: "not_found" });
  });

  /**
   * The first coach conversation.
   *
   * `greeting` is null once they have met — the client should fall straight
   * through to normal chat rather than replaying an introduction.
   */
  app.get("/coach/welcome", { preHandler: requireAuth }, async (req) =>
    coachWelcome(req.userId));

  /** Stores what they said, as they said it. */
  app.post("/coach/welcome/reply", { preHandler: requireAuth }, async (req) => {
    const { topic, reply } = z.object({
      topic: z.string().max(20),
      reply: z.string().min(1).max(500),
    }).parse(req.body);

    await recordWelcomeReply(req.userId, topic, reply);
    return { saved: true };
  });

  // ── sleep ─────────────────────────────────────────────────────────────────
  /**
   * Sleep coaching built on timing, not stages.
   *
   * A phone can tell when someone fell asleep and woke up; it cannot reliably
   * tell REM from deep. Regularity is both measurable and actionable, which is
   * why it is the headline here.
   */
  app.get("/sleep/summary", { preHandler: requireAuth }, async (req) => {
    const summary = await sleepSummary(req.userId, req.tz);

    return {
      ...summary,
      // Pre-formatted so the client never has to reason about midnight
      // wrap-around.
      avg_bedtime: clockLabel(summary.avgBedtimeMin),
      avg_wake: clockLabel(summary.avgWakeMin),
      avg_duration_hours: summary.avgDurationMin == null
        ? null
        : Math.round(summary.avgDurationMin / 60 * 10) / 10,
    };
  });

  // ── notifications ─────────────────────────────────────────────────────────
  /**
   * Today's notifications, already filtered.
   *
   * The server decides *what* and *when*; the client schedules locally. There
   * is no APNs in this app, and this split has a real advantage anyway — the
   * judgement stays in one place and testable, while delivery survives a
   * server outage.
   *
   * Call once a day on foreground. Returning an empty list is a normal, common
   * and correct outcome.
   */
  app.get("/notifications/plan", { preHandler: requireAuth }, async (req) => {
    const result = await planNotifications(req.userId, req.tz);

    return {
      notifications: result.planned.map((n) => ({
        id: n.id,
        category: n.category,
        priority: n.priority,
        title: n.title,
        body: n.body,
        deeplink: n.deeplink ?? null,
        deliver_at: n.deliverAt,
      })),
      // Visible so the decisions can be inspected rather than guessed at.
      suppressed: result.suppressed,
    };
  });

  /**
   * Engagement. Without this the engine cannot learn which notifications this
   * person actually wants, and keeps sending ones they never open.
   */
  app.post("/notifications/:id/event", { preHandler: requireAuth }, async (req, reply) => {
    const { id } = z.object({ id: z.string().uuid() }).parse(req.params);
    const { event } = z.object({
      event: z.enum(["sent", "opened", "dismissed", "acted"]),
    }).parse(req.body);

    const result = await recordEngagement(req.userId, id, event);
    return result ?? reply.code(404).send({ error: "not_found" });
  });

  /** What the engine has learned about when this person opens things. */
  app.get("/notifications/engagement", { preHandler: requireAuth }, async (req) => {
    const rows = await q<any>(
      `SELECT category,
              SUM(sent)::int AS sent, SUM(opened)::int AS opened,
              SUM(dismissed)::int AS dismissed, SUM(acted)::int AS acted
         FROM notification_engagement
        WHERE user_id = $1
        GROUP BY category
        ORDER BY sent DESC`,
      [req.userId]
    );

    return {
      by_category: rows.map((r: any) => ({
        ...r,
        open_rate: r.sent ? Math.round((r.opened / r.sent) * 100) : null,
      })),
      enough_data: rows.some((r: any) => r.sent >= 3),
    };
  });

  // ── what SnapCal knows about you ──────────────────────────────────────────
  /**
   * Personalization has to be visible and correctable, or it reads as the app
   * making things up about you.
   */
  app.get("/brain/memories", { preHandler: requireAuth }, async (req) => {
    const rows = await allMemories(req.userId);
    const byLayer: Record<string, any[]> = {};

    for (const m of rows) {
      (byLayer[m.layer] ??= []).push({
        id: m.id,
        content: m.content,
        confidence: Number(m.confidence),
        evidence_count: m.evidence_count,
        user_edited: m.user_edited,
        since: m.valid_from,
      });
    }

    return {
      layers: byLayer,
      total: rows.length,
      // Plain-language labels for the UI, so the screen never says "semantic".
      labels: {
        semantic: "Things I've learned about you",
        routine: "Your usual patterns",
        preference: "How you like to be coached",
        procedural: "What works for you",
        episodic: "Notable moments",
      },
    };
  });

  app.patch("/brain/memories/:id", { preHandler: requireAuth }, async (req, reply) => {
    const { id } = z.object({ id: z.string().uuid() }).parse(req.params);
    const { content } = z.object({ content: z.string().min(3).max(200) }).parse(req.body);

    const updated = await editMemory(req.userId, id, content);
    return updated ?? reply.code(404).send({ error: "not_found" });
  });

  app.delete("/brain/memories/:id", { preHandler: requireAuth }, async (req, reply) => {
    const { id } = z.object({ id: z.string().uuid() }).parse(req.params);
    const gone = await forgetMemory(req.userId, id);
    return gone ? { deleted: true } : reply.code(404).send({ error: "not_found" });
  });

  /**
   * Runs extraction over logged behaviour. Cheap and idempotent — consolidation
   * reinforces rather than duplicating, so calling it repeatedly is safe.
   */
  app.post("/brain/learn", { preHandler: requireAuth }, async (req) => {
    const [routines, outcomes] = await Promise.all([
      learnRoutines(req.userId),
      learnFromOutcomes(req.userId),
    ]);

    const all = [...routines, ...outcomes];
    return {
      added: all.filter((r) => r.action === "ADD").length,
      updated: all.filter((r) => r.action === "UPDATE").length,
      reinforced: all.filter((r) => r.action === "REINFORCE").length,
      unchanged: all.filter((r) => r.action === "NOOP").length,
      details: all,
    };
  });

  // ── recommendations and their outcomes ────────────────────────────────────
  /**
   * The learning loop. Without recording what was suggested and whether it was
   * followed, the coach cannot tell a lever that works for this person from
   * one that does not.
   */
  app.get("/recommendations", { preHandler: requireAuth }, async (req) => {
    const { status } = z.object({
      status: z.enum(["pending", "accepted", "dismissed", "completed", "all"]).default("pending"),
    }).parse(req.query);

    const rows = status === "all"
      ? await q(`SELECT * FROM recommendations WHERE user_id = $1
                  ORDER BY offered_on DESC LIMIT 50`, [req.userId])
      : await q(`SELECT * FROM recommendations WHERE user_id = $1 AND status = $2
                  ORDER BY offered_on DESC LIMIT 50`, [req.userId, status]);

    return { recommendations: rows };
  });

  app.post("/recommendations/:id/respond", { preHandler: requireAuth }, async (req, reply) => {
    const { id } = z.object({ id: z.string().uuid() }).parse(req.params);
    const { status, feedback } = z.object({
      status: z.enum(["accepted", "dismissed", "completed"]),
      feedback: z.string().max(300).optional(),
    }).parse(req.body);

    const updated = await one<any>(
      `UPDATE recommendations
          SET status = $3, responded_at = now()
        WHERE id = $2 AND user_id = $1
        RETURNING id, domain, action, status`,
      [req.userId, id, status]
    );

    if (!updated) return reply.code(404).send({ error: "not_found" });

    if (feedback) {
      await q(
        `INSERT INTO recommendation_outcomes
           (recommendation_id, user_id, user_feedback, direction)
         VALUES ($1,$2,$3,'unknown')`,
        [id, req.userId, feedback]
      );
    }

    return updated;
  });

  /** How well advice has landed — powers the procedural memory layer. */
  app.get("/recommendations/effectiveness", { preHandler: requireAuth }, async (req) => {
    const rows = await q<any>(
      `SELECT r.domain,
              COUNT(*)::int AS offered,
              COUNT(*) FILTER (WHERE r.status = 'completed')::int AS completed,
              COUNT(*) FILTER (WHERE r.status = 'dismissed')::int AS dismissed,
              COUNT(*) FILTER (WHERE o.direction = 'improved')::int AS improved
         FROM recommendations r
         LEFT JOIN recommendation_outcomes o ON o.recommendation_id = r.id
        WHERE r.user_id = $1
        GROUP BY r.domain
        ORDER BY offered DESC`,
      [req.userId]
    );

    return {
      by_domain: rows.map((r: any) => ({
        ...r,
        completion_rate: r.offered ? Math.round((r.completed / r.offered) * 100) : null,
      })),
      // Below this, rates are noise rather than signal.
      enough_data: rows.some((r: any) => r.offered >= 4),
    };
  });
}
