import Foundation

/// Daily check-in questions.
///
/// These are written here, in code, and chosen by rules — they are never
/// generated by a language model. A notification arrives unannounced, is not
/// reviewed by anyone before it appears, and cannot be corrected once sent. A
/// model writing "how is your chest pain today?" to someone who logged chest
/// discomfort last week would be a serious failure, and there is no way to catch
/// it before it lands on a lock screen.
///
/// So the model's role stays where it can be checked: answering the user once
/// they open the app. The nudge itself is deterministic.
enum CheckInPrompts {

    struct Prompt: Equatable, Sendable {
        let title: String
        let body: String
        /// Pre-filled into the coach when the notification is tapped, so the
        /// conversation starts on the thing the nudge was about.
        let coachQuestion: String
    }

    /// Everything known about the user's day, as plain facts.
    struct Context: Sendable {
        var readingsToday: Int = 0
        var daysSinceLastReading: Int?
        var readingCount: Int = 0
        var hasMedications: Bool = false
        var dosesOutstandingToday: Int = 0
        var sodiumLoggedToday: Bool = false
        var lastSymptomDaysAgo: Int?
        var hasUpcomingAppointment: Bool = false
        var daysUntilAppointment: Int?
        /// True when the last reading sat above the user's own recent average by
        /// a meaningful margin. Never an interpretation — just the comparison.
        var latestAboveOwnAverage: Bool = false
    }

    /// Picks one prompt for today.
    ///
    /// Ordered by usefulness, not variety: a missed dose matters more than a
    /// general check-in, so it wins. Returns nil when there is nothing worth
    /// saying — a notification that exists only to be sent trains people to
    /// ignore the ones that matter.
    static func todaysPrompt(for context: Context) -> Prompt? {
        // Nothing recorded at all: the app cannot say anything useful yet.
        if context.readingCount == 0 {
            return Prompt(
                title: "Ready when you are",
                body: "Your first reading gives BP Coach something to work with.",
                coachQuestion: "How should I take my first reading?"
            )
        }

        if context.dosesOutstandingToday > 0 {
            let count = context.dosesOutstandingToday
            return Prompt(
                title: "Medicine check",
                body: "\(count) dose\(count == 1 ? "" : "s") still to mark today.",
                coachQuestion: "Help me stay on top of my medicines."
            )
        }

        if let days = context.daysSinceLastReading, days >= 3 {
            return Prompt(
                title: "It has been \(days) days",
                body: "A reading today would keep your trend meaningful.",
                coachQuestion: "Does a gap in my readings affect what my trend shows?"
            )
        }

        if let days = context.daysUntilAppointment, days <= 3, context.hasUpcomingAppointment {
            return Prompt(
                title: days == 0 ? "Appointment today" : "Appointment in \(days) days",
                body: "BP Coach can prepare a summary to take with you.",
                coachQuestion: "What should I ask my doctor at this visit?"
            )
        }

        // Stated as a comparison, not a judgement — the safety engine decides
        // urgency, and a notification must not imply anything it cannot support.
        if context.latestAboveOwnAverage {
            return Prompt(
                title: "Today's reading",
                body: "Your last reading sat above your recent average. Worth a second one later?",
                coachQuestion: "Why might today's reading be higher than my average?"
            )
        }

        if context.readingsToday == 0 {
            return Prompt(
                title: "How are you doing today?",
                body: "A reading now keeps your picture up to date.",
                coachQuestion: "What does my recent pattern look like?"
            )
        }

        if !context.sodiumLoggedToday, context.readingCount >= 5 {
            return Prompt(
                title: "Anything salty today?",
                body: "Logging food helps connect what you eat to your numbers.",
                coachQuestion: "How does sodium affect blood pressure?"
            )
        }

        if let days = context.lastSymptomDaysAgo, days >= 14 {
            return Prompt(
                title: "Feeling alright?",
                body: "It has been a while since you noted how you feel.",
                coachQuestion: "Which symptoms are worth recording?"
            )
        }

        // Nothing needs saying today.
        return nil
    }

    /// Every prompt, for tests and for the settings preview.
    static var allPossiblePrompts: [Prompt] {
        [
            Context(readingCount: 0),
            Context(readingCount: 10, hasMedications: true, dosesOutstandingToday: 2),
            Context(daysSinceLastReading: 5, readingCount: 10),
            Context(readingCount: 10, hasUpcomingAppointment: true, daysUntilAppointment: 2),
            Context(readingCount: 10, latestAboveOwnAverage: true),
            Context(readingsToday: 0, readingCount: 10),
            Context(readingsToday: 1, readingCount: 10),
            Context(readingsToday: 1, readingCount: 10, sodiumLoggedToday: true,
                    lastSymptomDaysAgo: 20),
        ].compactMap(todaysPrompt)
    }
}
