import Foundation

/// Daily check-in questions.
///
/// These are written here, in code, and chosen by rules — they are never
/// generated by a language model. A notification arrives unannounced, is not
/// reviewed by anyone before it appears, and cannot be corrected once sent. A
/// model writing "how is your chest pain today?" to someone who logged chest
/// discomfort last week would be a serious failure, and there is no way to catch
/// it before it lands on a lock screen.
///
/// So the model's role stays where it can be checked: answering the user once
/// they open the app. The nudge itself is deterministic.
enum CheckInPrompts {

    struct Prompt: Equatable, Sendable {
        let title: String
        let body: String
        /// Pre-filled into the coach when the notification is tapped, so the
        /// conversation starts on the thing the nudge was about.
        let coachQuestion: String
    }

    /// Everything known about the user's day, as plain facts.
    struct Context: Sendable {
        /// Whether the user has ever set these up. Distinct from "none due
        /// today": someone with no medicines at all needs to be told where to
        /// add them, not reminded about doses that do not exist.
        var hasAnyAppointment: Bool = false
        var readingsToday: Int = 0
        var daysSinceLastReading: Int?
        var readingCount: Int = 0
        var hasMedications: Bool = false
        var dosesOutstandingToday: Int = 0
        var sodiumLoggedToday: Bool = false
        var lastSymptomDaysAgo: Int?
        var hasUpcomingAppointment: Bool = false
        var daysUntilAppointment: Int?
        /// Days since an appointment that has already happened, if it was
        /// recent. The day after a visit is when medication changes are worth
        /// asking about — and when the person still remembers what was said.
        var daysSinceAppointment: Int?
        /// True when the last reading sat above the user's own recent average by
        /// a meaningful margin. Never an interpretation — just the comparison.
        var latestAboveOwnAverage: Bool = false
    }

    /// Picks one prompt for today.
    ///
    /// Ordered by usefulness, not variety: a missed dose matters more than a
    /// general check-in, so it wins. Returns nil when there is nothing worth
    /// saying — a notification that exists only to be sent trains people to
    /// ignore the ones that matter.
    static func todaysPrompt(for context: Context) -> Prompt? {
        // Nothing recorded at all: the app cannot say anything useful yet.
        if context.readingCount == 0 {
            return Prompt(
                title: "Ready when you are",
                body: "Your first reading gives BP Coach something to work with.",
                coachQuestion: "How should I take my first reading?"
            )
        }

        // Setup guidance comes before daily nudges. Reminding someone to take a
        // reading is less useful than telling them the app can remind them about
        // medicines they have not added yet — and each of these names the exact
        // path, because "you can add medicines" without saying where is a
        // half-finished instruction.
        if !context.hasMedications, context.readingCount >= 3 {
            return Prompt(
                title: "Taking any medicines?",
                body: "Add them under Add → Medicine Reminder and BP Coach will remind you each day.",
                coachQuestion: "How do I add my medicines and set reminders?"
            )
        }

        if !context.hasAnyAppointment, context.readingCount >= 5 {
            return Prompt(
                title: "Seeing your doctor soon?",
                body: "Add it under Add → Doctor Appointment. BP Coach will remind you and prepare a summary.",
                coachQuestion: "How do I add a doctor appointment and get a summary to take with me?"
            )
        }

        if context.dosesOutstandingToday > 0 {
            let count = context.dosesOutstandingToday
            return Prompt(
                title: "Medicine check",
                body: "\(count) dose\(count == 1 ? "" : "s") still to mark today.",
                coachQuestion: "Help me stay on top of my medicines."
            )
        }

        if let days = context.daysSinceLastReading, days >= 3 {
            return Prompt(
                title: "It has been \(days) days",
                body: "A reading today would keep your trend meaningful.",
                coachQuestion: "Does a gap in my readings affect what my trend shows?"
            )
        }

        // Ranked above the pre-appointment reminder: a visit that already
        // happened may have changed a prescription, and stale medication data
        // is worse than a missed nudge.
        if let days = context.daysSinceAppointment, days >= 0, days <= 2 {
            return Prompt(
                title: "How did your appointment go?",
                body: "If anything changed with your medicines, update them under Add → Medicine Reminder.",
                coachQuestion: "My doctor appointment was recent. What should I update in the app?"
            )
        }

        if let days = context.daysUntilAppointment, days <= 3, context.hasUpcomingAppointment {
            return Prompt(
                title: days == 0 ? "Appointment today" : "Appointment in \(days) days",
                body: "BP Coach can prepare a summary to take with you.",
                coachQuestion: "What should I ask my doctor at this visit?"
            )
        }

        // Stated as a comparison, not a judgement — the safety engine decides
        // urgency, and a notification must not imply anything it cannot support.
        if context.latestAboveOwnAverage {
            return Prompt(
                title: "Today's reading",
                body: "Your last reading sat above your recent average. Worth a second one later?",
                coachQuestion: "Why might today's reading be higher than my average?"
            )
        }

        if context.readingsToday == 0 {
            return Prompt(
                title: "How are you doing today?",
                body: "A reading now keeps your picture up to date.",
                coachQuestion: "What does my recent pattern look like?"
            )
        }

        if !context.sodiumLoggedToday, context.readingCount >= 5 {
            return Prompt(
                title: "Anything salty today?",
                body: "Logging food helps connect what you eat to your numbers.",
                coachQuestion: "How does sodium affect blood pressure?"
            )
        }

        if let days = context.lastSymptomDaysAgo, days >= 14 {
            return Prompt(
                title: "Feeling alright?",
                body: "It has been a while since you noted how you feel.",
                coachQuestion: "Which symptoms are worth recording?"
            )
        }

        // Nothing needs saying today.
        return nil
    }

    /// Builds the context from stored records.
    ///
    /// Lives here rather than in a view so Home and the settings test cannot
    /// drift apart — a test that builds its context differently from the real
    /// scheduler would prove nothing.
    @MainActor
    static func context(
        profileID: UUID,
        readings: [BPReading],
        medications: [Medication],
        doses: [MedicationDose],
        lifestyle: [LifestyleEntry],
        symptoms: [SymptomEntry],
        appointments: [Appointment]
    ) -> Context {
        let calendar = Calendar.current
        let mine = readings.filter { $0.profileID == profileID }
        let myAppointments = appointments.filter { $0.profileID == profileID }

        var context = Context()
        context.readingCount = mine.count
        context.readingsToday = mine.filter { calendar.isDateInToday($0.recordedAt) }.count
        context.hasMedications = medications.contains {
            $0.profileID == profileID && !$0.isArchived
        }
        context.hasAnyAppointment = !myAppointments.isEmpty
        context.dosesOutstandingToday = doses.filter {
            $0.profileID == profileID
                && calendar.isDateInToday($0.scheduledFor)
                && $0.status == .scheduled
        }.count
        context.sodiumLoggedToday = lifestyle.contains {
            $0.profileID == profileID && $0.kind == .sodium
                && calendar.isDateInToday($0.recordedAt)
        }

        if let latest = mine.max(by: { $0.recordedAt < $1.recordedAt }) {
            context.daysSinceLastReading = calendar.dateComponents(
                [.day], from: latest.recordedAt, to: .now
            ).day
            if let average = BPStatistics.homeAverage(mine, days: 30), average.count >= 3 {
                context.latestAboveOwnAverage = latest.systolic >= average.systolic + 8
            }
        }

        if let recent = symptoms
            .filter({ $0.profileID == profileID })
            .max(by: { $0.recordedAt < $1.recordedAt }) {
            context.lastSymptomDaysAgo = calendar.dateComponents(
                [.day], from: recent.recordedAt, to: .now
            ).day
        }

        if let next = myAppointments.filter(\.isUpcoming)
            .min(by: { $0.scheduledFor < $1.scheduledFor }) {
            context.hasUpcomingAppointment = true
            context.daysUntilAppointment = calendar.dateComponents(
                [.day], from: .now, to: next.scheduledFor
            ).day
        }

        // The most recent appointment that has already happened.
        if let last = myAppointments.filter({ !$0.isUpcoming })
            .max(by: { $0.scheduledFor < $1.scheduledFor }) {
            context.daysSinceAppointment = calendar.dateComponents(
                [.day], from: last.scheduledFor, to: .now
            ).day
        }

        return context
    }

    /// Every prompt the rules can produce, for tests and previews.
    ///
    /// Built by mutation rather than the memberwise initialiser: that init
    /// demands arguments in declaration order, so adding a field to `Context`
    /// silently breaks every fixture here.
    static var allPossiblePrompts: [Prompt] {
        var contexts: [Context] = []

        // No readings at all.
        contexts.append(Context())

        /// A context where setup is done, so the later rules are reachable.
        func settled() -> Context {
            var context = Context()
            context.readingCount = 10
            context.readingsToday = 1
            context.hasMedications = true
            context.hasAnyAppointment = true
            return context
        }

        // No medicines yet.
        var noMedicines = Context()
        noMedicines.readingCount = 5
        contexts.append(noMedicines)

        // Medicines but no appointment.
        var noAppointment = Context()
        noAppointment.readingCount = 10
        noAppointment.hasMedications = true
        contexts.append(noAppointment)

        var doses = settled()
        doses.dosesOutstandingToday = 2
        contexts.append(doses)

        var afterVisit = settled()
        afterVisit.daysSinceAppointment = 1
        contexts.append(afterVisit)

        var gap = settled()
        gap.daysSinceLastReading = 5
        contexts.append(gap)

        var upcoming = settled()
        upcoming.hasUpcomingAppointment = true
        upcoming.daysUntilAppointment = 2
        contexts.append(upcoming)

        var aboveAverage = settled()
        aboveAverage.latestAboveOwnAverage = true
        contexts.append(aboveAverage)

        var noneToday = settled()
        noneToday.readingsToday = 0
        contexts.append(noneToday)

        var noSodium = settled()
        contexts.append(noSodium)

        var oldSymptom = settled()
        oldSymptom.sodiumLoggedToday = true
        oldSymptom.lastSymptomDaysAgo = 20
        contexts.append(oldSymptom)

        return contexts.compactMap(todaysPrompt)
    }
}
